### ISSUE TITLE
Nobrainer

### ISSUE THREAD

**Issue by hvgazula** [ohbm/hackathon2023#19]
### Title

Nobrainer: A framework for developing neural network models for 3D image processing

### Short description and the goals for the OHBM BrainHack

Nobrainer-zoo is a toolbox with a collection of deep learning neuroimaging models that eases the use of pre-trained models for various applications. Nobrainer-zoo provides the required environment with all the dependencies for training/inference of models.

During the hackathon, we aim to incorporate new models into the zoo along the lines of existing ones. Some of the models include TopoFit, CorticalFlow, Vox2Cortex, CortexODE, PialNN, and many other deep learning-based neuroimaging models that users would want to see as part of the nobrainer-zoo.

Tasks are designed to be really simple and to facilitate this model integration, we also provide a step-by-step documentation/guide that can be found at https://github.com/neuronets/trained-models/blob/master/add_model_instructions.md

### Link to the Project

https://github.com/neuronets/nobrainer-zoo.git

### Project lead

@satra 

### Main Hub

Montreal

### Other Hub covered by the leaders

- [X] Montreal
- [ ] Asia / Pacific
- [ ] Europe / Middle East / Africa
- [X] Americas

### Skills

Python, Datalad, Docker, Singularity

### Recommended tutorials for new contributors

- [ ] [Set up a brainhack friendly computing environment](https://school-brainhack.github.io/modules/installation/)
- [ ] [A introduction to Bash](https://school-brainhack.github.io/modules/introduction_to_terminal/)
- [x] [Python: Writing a script](https://school-brainhack.github.io/modules/python_scripts/)
- [ ] [Python: Data analysis with Python](https://school-brainhack.github.io/modules/python_data_analysis/)
- [ ] [Python: Visualisation](https://school-brainhack.github.io/modules/python_visualization/)
- [ ] [Machine learning basics](https://school-brainhack.github.io/modules/machine_learning_basics/)
- [ ] [BIDS](https://school-brainhack.github.io/modules/bids/)
- [ ] [Machine learning for neuroimaging](https://school-brainhack.github.io/modules/machine_learning_neuroimaging/)
- [ ] [VCS: Using Git and Github](https://school-brainhack.github.io/modules/git_github/)
- [x] [VCS: Data management with Datalad](https://school-brainhack.github.io/modules/datalad/)
- [ ] [Virtualization](https://school-brainhack.github.io/modules/containers/)
- [ ] High Performance Computing: [Oracle cloud resource](https://brainhack.org/brainhack_cloud/)

### Good first issues

https://github.com/neuronets/trained-models/issues/51

### Short name for the Discord chat channel (~15 chars)

nobrainer-project

### Please read and follow the OHBM Code of Conduct

- [X] I agree to follow the OHBM Code of Conduct during the hackathon

**Comment by hvgazula** [comment]
Hello @anibalsolon! I understand that this project hasn't been added to the discord list. Could you please let me know what needs to be done to add there?

**Comment by anibalsolon** [comment]
hey! it should be here: https://discord.com/channels/920383461829795920/1131262858307575870

**Comment by hvgazula** [comment]
Thank you.

**Comment by ufangYang** [comment]
hi @hvgazula   can you provide the content and/or figure for this project to be added to Brainhack Proceeding 2023 by 15th May? Also, please don't forget to fill out your team member's details using this form: https://forms.gle/Ku3AVHcXvpUqVVkV7 . Cheers

**Comment by satra** [comment]
@ufangYang - i don't believe anything was done on this during the hackathon. let's close this.

**Comment by ufangYang** [comment]
@satra, thanks, got it!
