### ISSUE TITLE
update issue template to recent brainhack school tutorials

### ISSUE THREAD

**Issue by pbellec** [ohbm/hackathon2023#3]
The latest version of the brainhack school modules can be found at
https://school.brainhackmtl.org/modules/

Module content is now updated and maintained by the community and the url I just shared should be stable for years to come.

Sorry for not looping you in earlier, I had not realized you incorporated module links in the project template (which is very cool btw)

Can't wait for the hackathon!

**Comment by anibalsolon** [comment]
Thank you @pbellec ! We will update with the new links

**Comment by anibalsolon** [comment]
Closed by 4353a2d04def2d1cf8def26a92aabb724c343975
