### ISSUE TITLE
ShareStats

### ISSUE THREAD

**Issue by agt24** [ohbm/hackathon2023#34]
### Title

Solving the NIH's Underpants Problem with open bibliometrics and OpenAlex.

### Short description and the goals for the OHBM BrainHack

We plan to build an open and transparent source resource where program officers can obtain information about data sharing statements for a given paper. The interface will provide aggregation by investigator,  institution, grant, etc. It will also provide mechanism for investigators to submit correction  (PRs)

### Link to the Project

https://tokyo.o18s.com/
https://openalex.org/

### Project lead

Adam Thomas @agt24 Discord:adamtNIH

### Main Hub

Montreal

### Other Hub covered by the leaders

- [X] Montreal
- [ ] Asia / Pacific
- [ ] Europe / Middle East / Africa
- [ ] Americas

### Skills

- Front end (java script)
- containers
- CI
- Python
- Github

### Recommended tutorials for new contributors

- [ ] [Set up a brainhack friendly computing environment](https://school-brainhack.github.io/modules/installation/)
- [x] [A introduction to Bash](https://school-brainhack.github.io/modules/introduction_to_terminal/)
- [x] [Python: Writing a script](https://school-brainhack.github.io/modules/python_scripts/)
- [x] [Python: Data analysis with Python](https://school-brainhack.github.io/modules/python_data_analysis/)
- [ ] [Python: Visualisation](https://school-brainhack.github.io/modules/python_visualization/)
- [ ] [Machine learning basics](https://school-brainhack.github.io/modules/machine_learning_basics/)
- [ ] [BIDS](https://school-brainhack.github.io/modules/bids/)
- [ ] [Machine learning for neuroimaging](https://school-brainhack.github.io/modules/machine_learning_neuroimaging/)
- [ ] [VCS: Using Git and Github](https://school-brainhack.github.io/modules/git_github/)
- [ ] [VCS: Data management with Datalad](https://school-brainhack.github.io/modules/datalad/)
- [ ] [Virtualization](https://school-brainhack.github.io/modules/containers/)
- [ ] High Performance Computing: [Oracle cloud resource](https://brainhack.org/brainhack_cloud/)

### Short name for the Discord chat channel (~15 chars)

sharestats

### Please read and follow the OHBM Code of Conduct

- [X] I agree to follow the OHBM Code of Conduct during the hackathon

**Comment by ufangYang** [comment]
hi @agt24   can you provide the content and/or figure for this project to be added to Brainhack Proceeding 2023 by 15th May? Also, please don't forget to fill out your team member's details using this form: https://forms.gle/Ku3AVHcXvpUqVVkV7 . Cheers
